# Conway's Game of Life Benchmark Configuration

[general]
# The number of iterations to run for each benchmark
iterations = 3

# The maximum grid size to benchmark (NxN)
max_size = 1000

# The number of generations to simulate for each benchmark
generations = 100

[patterns]
# Patterns to benchmark
patterns = [
    "glider",
    "blinker",
    "pulsar",
    "glider_gun",
    "lwss",
    "r-pentomino",
    "acorn"
]

[sizes]
# Grid sizes to benchmark (width, height)
sizes = [
    [100, 100],
    [250, 250],
    [500, 500],
    [1000, 1000]
]

[optimization]
# Enable rayon parallel processing
parallel = true

# Number of threads to use (0 = auto)
threads = 0

# Use bit-packed representation (more memory efficient)
bit_packed = true